apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: *****
  MYSQL_PASSWORD: *****
  MYSQL_USER: merve
  MYSQL_DATABASE: phonebook
  MYSQL_DATABASE_HOST: mysql-service
