apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers: 
      - image: emrverskn/webserver
        name: webservercontainer
        envFrom:
        - secretRef:
            name: mysql-secret
        ports: 
        - containerPort: 80
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers: 
      - image: emrverskn/webserver
        name: resultservercontainer
        envFrom:
        - secretRef:
            name: mysql-secret
        ports: 
        - containerPort: 80